# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# shell commands
shell_command: !include shell_command.yaml

# ============================================================================
# PACKAGES - Voeg deze regel toe voor modulaire configuratie
# ============================================================================
homeassistant:
  packages: !include_dir_named packages
